<?php

use Drupal\webform\Entity\WebformSubmission;
use Drupal\webform\WebformSubmissionForm;
use Drupal\drmanage\Controller\AwsformController;

function drmanage_theme($existing, $type, $theme, $path) {
  return [
    'dashboard' => [
      'variables' => [
        'path' => $path . '/templates',
        'something' => 'This is something.',
      ]
    ],
    'listcontents' => [
      'variables' => [
        'path' => $path . '/templates',
        'content' => '',
      ]
    ],
    // add more templates as needed
  ];
}

function drmanage_webform_submission_insert(WebformSubmission $webform) {

  $data = $webform->getData();

  $url = $data['website_url'];

  $postdata = [
    'access_key' => $data['aws_access_key'],
    'secret_key' => $data['aws_secret_key'],
    //'session_token' => $data['aws_session_token'],
    'bucket_location' => $data['default_region'],
    'host_base' => 's3.amazonaws.com',
    'host_bucket' => $data['dns_style_bucket_hostname']
  ];

  // TODO - proxy information

  // use key 'http' even if you send the request to https://...
  $options = [
    'http' => [
      'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
      'method'  => 'POST',
      'content' => http_build_query($postdata)
    ]
  ];

  $context  = stream_context_create($options);
  $result = file_get_contents($url, false, $context);
  if ($result === FALSE) {
    drupal_set_message('Failed for some reason', 'error');
  }
  else {
    drupal_set_message('Success! Maybe. '. print_r($result, true));
  }
}
